grpcport = "50051"
username = "testuser"
password = "testPW"
baseurl = "http://localhost:8000"
urlget = "/te?q=123+eq+123 AND "
urlput = "/users"
urlaccounts = "/accounts"
urlfilter =  [[ "aa::bb::cc", ["AA", "BB"]]]
#urlfilter =  [[ "aa::bb::cc", ["AA","BB","CC" ]], [ "ggggg", ["aa","bb","cc" ] ]]
printmode = false
checkmode = false
filemode = true
entries = 10
filter1 = "AAccount"
filter2 = "Update"
listof = "AAccount"
attr = "Process Instance.Task Information.Target User"
filelist = "path2.csv"

