
[grpc]
grpcport = "http://[::1]:50051"
username = "testuser"
password = "testPW"
baseurl = "http://172.27.214.136:8000"


#[debug]
#echo = true
# --- conf_map ---
# Each key here (e.g., "trader1") maps to a TraderConf configuration.
[[Stockconfig.ORCL]]
variant = "type1"
symbol = "ORCL"
price_label = "Close"
shares_to_buy = 10
indicator = [
    { type = "BollingerBands" },
    { type = "ExponentialMovingAverage" },
    { type = "RelativeStrengthIndex" },
]
buffersize = 10
buff = { capacity = 10, data = [] }

[[Stockconfig.ORCL]]
variant = "type2"
symbol = "ORCL"
price_label = "Open"
shares_to_buy = 25
indicator = [{ type = "SimpleMovingAverage" }]
buffersize = 10
buff = { capacity = 5, data = [] }


[[Stockconfig.ORCL2]]
variant = "type1"
symbol = "ORCL"
price_label = "Close"
shares_to_buy = 100
indicator = [
    { type = "BollingerBands" },
    { type = "ExponentialMovingAverage" },
    { type = "RelativeStrengthIndex" },
]
buffersize = 20
buff = { capacity = 20, data = [] }

# Optional ActionValidate configuration.
#[conf_map.action_validate]
# Example fields – adapt these to your ActionValidate struct.
#threshold = 10
#mode = "strict"

# Optional IndiValidate configuration.
#[conf_map.indi_validate]
# Example fields – adapt these to your IndiValidate struct.
#enabled = true
#tolerance = 0.05
