grpcport = "http://[::1]:50051"
username = "testuser"
password = "testPW"
baseurl = "http://localhost:8000"
urlget = "/te?q=123+eq+123 AND "
urlfilter = [["aa::bb::cc", ["AA", "BB"]]]
entries = 5
filter1 = "AAccount"
filter2 = "Update"
urlput = "/users"
printmode = true
checkmode = false
filemode = false
filelist = "list.csv"
